import { persianLanguage } from '@/data/persian';
import './globals.css';
import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import React from 'react';
const inter = Vazirmatn({ subsets: ['arabic', 'latin'] });

export const metadata: Metadata = {
  title: persianLanguage.storeName,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode;
}) {
  return (
    <html lang='fa'>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
